#preload = /home/user/Downloads/berserker.png

preload = /home/user/Downloads/rainbow.jpg

wallpaper = eDP-1,/home/user/Downloads/rainbow.jpg

#wallpaper = eDP-1,/home/user/Downloads/berserker.png
#wallpaper = HDMI-A-1,/home/user/Downloads/berserker.png
